title = "Noam's Website About Software"
baseurl = "http://noamswebsite.com/"
languageCode = "en-us"
theme = "blank"
publishDir = "../noamswebsite_out"

[[menu.about]]
  url = "/resume.pdf"
  name = "Resume / CV (pdf)"
  weight = 10
[[menu.about]]
  name = "GitHub"
  url = "https://github.com/noam87"
  weight = 20
[[menu.about]]
  name = "Contact Me"
  url = "https://noam87.wufoo.com/forms/contact-me/"
  weight = 25
[[menu.about]]
  name = "Personal Blog"
  url = "https://noamswebsite.wordpress.com"
  weight = 30
